export  const corregimientos = [
{ id: 1, name: 'Bocas del Toro (Cabecera)', idDistrito: 1},
{ id: 2, name: 'Bastimentos', idDistrito: 1},
{ id: 3, name: 'Cauchero', idDistrito: 1},
{ id: 4, name: 'Punta Laurel', idDistrito: 1},
{ id: 5, name: 'Tierra Oscura', idDistrito: 1},
{ id: 6, name: 'Changuinola (Cabecera)',idDistrito: 2},
{ id: 7, name: 'Almirante',idDistrito: 2},
{ id: 8, name: 'Guabito',idDistrito: 2},
{ id: 9, name: 'Teribe',idDistrito: 2},
{ id: 10, name: 'Valle del Risco',idDistrito: 2},
{ id: 11,name: 'El Empalme',idDistrito: 2},
{ id: 12,name: 'Las Tablas',idDistrito: 2},
{ id: 13, name: 'Cochigró',idDistrito: 2},
{ id: 14,name: 'La Gloria',idDistrito: 2},
{ id: 15,name: 'Las Delicias.',idDistrito: 2},
{ id: 16, name: 'Nance del Risco',idDistrito: 2},
{ id: 17, name: 'Valle de Agua Arriba',idDistrito: 2},
{ id: 18, name: 'Chiriquí Grande (Cabecera)',idDistrito: 3},
{ id: 19, name: 'Miramar',idDistrito: 3},
{ id: 20, name: 'Punta Peña',idDistrito: 3},
{ id: 21, name: 'Punta Robalo',idDistrito: 3},
{ id: 22, name: 'Rambala',idDistrito: 3},
{ id: 23, name: 'Bajo Cedro',idDistrito: 3},
{ id: 24, name: 'Aguadulce (Cabecera)', idDistrito: 4},
{ id: 25,name: 'El Cristo', idDistrito: 4},
{ id: 26,name: 'El Roble', idDistrito: 4},
{ id: 27, name: 'Pocrí', idDistrito: 4},
{ id: 28, name: 'Barrios Unidos', idDistrito: 4},
{ id: 29, name: 'Antón (Cabecera)', idDistrito: 5},
{ id: 30, name: 'Cabuya', idDistrito: 5},
{ id: 31,name: 'El Chirú', idDistrito: 5},
{ id: 32,name: 'El Retiro', idDistrito: 5},
{ id: 33,name: 'El Valle', idDistrito: 5},
{ id: 34, name: 'Juan Díaz', idDistrito: 5},
{ id: 35, name: 'Río Hato', idDistrito: 5},
{ id: 36, name: 'San Juan de Dios', idDistrito: 5},
{ id: 37, name: 'Santa Rita', idDistrito: 5},
{ id: 38, name: 'Caballero', idDistrito: 5},
{ id: 39,name: 'La Pintada (Cabecera)',idDistrito: 6},
{ id: 40,name: 'El Harino',idDistrito: 6},
{ id: 41,name: 'El Potrero',idDistrito: 6},
{ id: 42,name: 'Llano Grande',idDistrito: 6},
{ id: 43, name: 'Piedras Gordas',idDistrito: 6},
{ id: 44,name: 'Las Lomas',idDistrito: 6},
{ id: 45,name: 'Llano Norte',idDistrito: 6},
{ id: 46, name: 'Natá (Cabecera)',idDistrito: 7},
{ id: 47, name: 'Capellanía',idDistrito: 7},
{ id: 48,name: 'El Caño',idDistrito: 7},
{ id: 49, name: 'Guzmán',idDistrito: 7},
{ id: 50,name: 'Las Huacas',idDistrito: 7},
{ id: 51, name: 'Toza',idDistrito: 7},
{ id: 52, name: 'Olá (Cabecera)',idDistrito: 8},
{ id: 53,name: 'El Copé',idDistrito: 8},
{ id: 54,name: 'El Palmar',idDistrito: 8},
{ id: 55,name: 'El Picacho',idDistrito: 8},
{ id: 56,name: 'La Pava',idDistrito: 8},
{ id: 57, name: 'Penonomé (Cabecera)',idDistrito: 9},
{ id: 58, name: 'Cañaveral',idDistrito: 9},
{ id: 59, name: 'Coclé',idDistrito: 9},
{ id: 60, name: 'Chiguirí Arriba',idDistrito: 9},
{ id: 61,name: 'El Coco',idDistrito: 9},
{ id: 62, name: 'Pajona',idDistrito: 9},
{ id: 63, name: 'Río Grande',idDistrito: 9},
{ id: 64, name: 'Río Indio',idDistrito: 9},
{ id: 65, name: 'Toabré',idDistrito: 9},
{ id: 66, name: 'Tulú',idDistrito: 9},
{ id: 67, name: 'Barrio Norte',idDistrito: 10},
{ id: 68, name: 'Barrio Sur',idDistrito: 10},
{ id: 69, name: 'Buena Vista',idDistrito: 10},
{ id: 70, name: 'Cativá',idDistrito: 10},
{ id: 71, name: 'Ciricito',idDistrito: 10},
{ id: 72, name: 'Cristóbal',idDistrito: 10},
{ id: 73,name: 'Escobal',idDistrito: 10},
{ id: 74,name: 'Limón',idDistrito: 10},
{ id: 75, name: 'Nueva Providencia',idDistrito: 10},
{ id: 76, name: 'Puerto Pilón',idDistrito: 10},
{ id: 77, name: 'Sabanitas',idDistrito: 10},
{ id: 78, name: 'Salamanca',idDistrito: 10},
{ id: 79, name: 'San Juan',idDistrito: 10},
{ id: 80, name: 'Santa Rosa',idDistrito: 10},
{ id: 81, name: 'Nuevo Chagres (Cabecera)',idDistrito: 11},
{ id: 82, name: 'Achiote',idDistrito: 11},
{ id: 83,name: 'El Guabo',idDistrito: 11},
{ id: 84,name: 'La Encantada',idDistrito: 11},
{ id: 85, name: 'Palmas Bellas.',idDistrito: 11},
{ id: 86, name: 'Piña',idDistrito: 11},
{ id: 87, name: 'Salud',idDistrito: 11},
{ id: 88, name: 'Miguel de la Borda (Cabecera)',idDistrito: 12},
{ id: 89, name: 'Coclé del Norte',idDistrito: 12},
{ id: 90,name: 'El Guásimo',idDistrito: 12},
{ id: 91, name: 'Gobea',idDistrito: 12},
{ id: 92, name: 'Río Indio',idDistrito: 12},
{ id: 93, name: 'San José del General',idDistrito: 12},
{ id: 94, name: 'Portobelo (Cabecera)',idDistrito: 13},
{ id: 95, name: 'Cacique',idDistrito: 13},
{ id: 96, name: 'Puerto Lindo o Garrote',idDistrito: 13},
{ id: 97, name:'Isla Grande',idDistrito: 13},
{ id: 98, name: 'María Chiquita',idDistrito: 13},
{ id: 99, name: 'Palenque (Cabecera)',idDistrito: 14},
{ id: 100, name: 'Cuango',idDistrito: 14},
{ id: 101, name: 'Miramar',idDistrito: 14},
{ id: 102, name: 'Nombre de Dios',idDistrito: 14},
{ id: 103, name: 'Palmira',idDistrito: 14},
{ id: 104, name: 'Playa Chiquita',idDistrito: 14},
{ id: 105, name: 'Santa Isabel',idDistrito: 14},
{ id: 106, name: 'Viento Frío',idDistrito: 14},
{ id: 107, name: 'Alanje (Cabecera)',idDistrito: 15},
{ id: 108, name: 'Divalá',idDistrito: 15},
{ id: 109,name: 'El Tejar',idDistrito: 15},
{ id: 110, name: 'Guarumal',idDistrito: 15},
{ id: 111, name: 'Palo Grande',idDistrito: 15},
{ id: 112, name: 'Querévalo',idDistrito: 15},
{ id: 113, name: 'Santo Tomás',idDistrito: 15},
{ id: 114, name: 'Canta Gallo',idDistrito: 15},
{ id: 115, name: 'Nuevo México',idDistrito: 15},
{ id: 116, name: 'Puerto Armuelles (Cabecera',idDistrito: 16},
{ id: 117,name: 'Limones',idDistrito: 16},
{ id: 118, name: 'Progreso',idDistrito: 16},
{ id: 119, name: 'Baco',idDistrito: 16},
{ id: 120, name: 'Rodolfo Aguilar Delgado',idDistrito: 16},
{ id: 121, name: 'Boquerón (Cabecera)',idDistrito: 17},
{ id: 122, name: 'Bágala',idDistrito: 17},
{ id: 123, name: 'Cordillera',idDistrito: 17},
{ id: 124, name: 'Guabal',idDistrito: 17},
{ id: 125, name: 'Guayabal',idDistrito: 17},
{ id: 126, name: 'Paraíso',idDistrito: 17},
{ id: 127, name: 'Pedregal',idDistrito: 17},
{ id: 128, name: 'Tijeras',idDistrito: 17},
{ id: 129, name: 'Bajo Boquete (Cabecera)',idDistrito: 18},
{ id: 130, name: 'Caldera',idDistrito: 18},
{ id: 131, name: 'Palmira',idDistrito: 18},
{ id: 132, name: 'Alto Boquete',idDistrito: 18},
{ id: 133, name: 'Jaramillo',idDistrito: 18},
{ id: 134,name: 'Los Naranjos',idDistrito: 18},
{ id: 135,name: 'La Concepción (Cabecera)',idDistrito: 19},
{ id: 136, name: 'Aserrío de Gariché',idDistrito: 19},
{ id: 137, name: 'Bugaba',idDistrito: 19},
{ id: 138, name: 'Cerro Punta',idDistrito: 19},
{ id: 139, name: 'Gómez',idDistrito: 19},
{ id: 140,name: 'La Estrella',idDistrito: 19},
{ id: 141, name: 'San Andrés',idDistrito: 19},
{ id: 142, name: 'Santa Marta',idDistrito: 19},
{ id: 143, name: 'Santa Rosa',idDistrito: 19},
{ id: 144, name: 'Santo Domingo',idDistrito: 19},
{ id: 145, name: 'Sortová',idDistrito: 19},
{ id: 146, name: 'Volcán',idDistrito: 19},
{ id: 147,name: 'El Bongo',idDistrito: 19},
{ id: 148, name: 'David (Cabecera',idDistrito: 20},
{ id: 149, name: 'Bijagual',idDistrito: 20},
{ id: 150, name: 'Cochea',idDistrito: 20},
{ id: 151, name: 'Chiriquí',idDistrito: 20},
{ id: 152, name: 'Guacá',idDistrito: 20},
{ id: 153,name: 'Las Lomas',idDistrito: 20},
{ id: 154, name: 'Pedrega',idDistrito: 20},
{ id: 155, name: 'San Carlos',idDistrito: 20},
{ id: 156, name: 'San Pablo Nuevo',idDistrito: 20},
{ id: 157, name: 'San Pablo Viejo',idDistrito: 20},
{ id: 158, name: 'Dolega (Cabecera)',idDistrito: 21},
{ id: 159, name: 'Dos Ríos',idDistrito: 21},
{ id: 160,name: 'Los Anastacios',idDistrito: 21},
{ id: 161, name: 'Potrerillos',idDistrito: 21},
{ id: 162, name: 'Potrerillos Abajo',idDistrito: 21},
{ id: 163, name: 'Rovira',idDistrito: 21},
{ id: 164, name: 'Tinajas',idDistrito: 21},
{ id: 165,name: 'Los Algarrobos',idDistrito: 21},
{ id: 166, name: 'Gualaca (Cabecera)',idDistrito: 22},
{ id: 167, name: 'Hornito',idDistrito: 22},
{ id: 168,name: 'Los Ángeles',idDistrito: 22},
{ id: 169, name: 'Paja de Sombrero',idDistrito: 22},
{ id: 170, name: 'Rincón',idDistrito: 22},
{ id: 171, name: 'Remedios (Cabecera)',idDistrito: 23},
{ id: 172,name: 'El Nancito',idDistrito: 23},
{ id: 173,name: 'El Porvenir',idDistrito: 23},
{ id: 174,name: 'El Puerto',idDistrito: 23},
{ id: 175, name: 'Santa Lucía',idDistrito: 23},
{ id: 176, name: 'Río Sereno (Cabecera',idDistrito: 24},
{ id: 177, name: 'Breñón',idDistrito: 24},
{ id: 178, name: 'Cañas Gordas',idDistrito: 24},
{ id: 179, name: 'Monte Lirio',idDistrito: 24},
{ id: 180, name: 'Plaza Caisán',idDistrito: 24},
{ id: 181, name: 'Santa Cruz',idDistrito: 24},
{ id: 182, name: 'Dominical',idDistrito: 24},
{ id: 183, name: 'Santa Clara',idDistrito: 24},
{ id: 184,name: 'Las Lajas (Cabecera)',idDistrito: 25},
{ id: 185, name: 'Juay',idDistrito: 25},
{ id: 186,name: 'Lajas Adentro',idDistrito: 25},
{ id: 187, name: 'San Félix',idDistrito: 25},
{ id: 188, name: 'Santa Cruz',idDistrito: 25},
{ id: 189, name: 'Horconcitos (Cabecera)',idDistrito: 26},
{ id: 190, name: 'Boca Chica',idDistrito: 26},
{ id: 191, name: 'Boca del Monte',idDistrito: 26},
{ id: 192, name: 'San Juan',idDistrito: 26},
{ id: 193, name: 'San Lorenzo',idDistrito: 26},
{ id: 194, name: 'Tolé (Cabecera)',idDistrito: 27},
{ id: 195, name: 'Bella Vista',idDistrito: 27},
{ id: 196, name: 'Cerro Viejo',idDistrito: 27},
{ id: 197,name: 'El Cristo',idDistrito: 27},
{ id: 198, name: 'Justo Fidel',idDistrito: 27},
{ id: 199,name: 'Lajas de Tolé',idDistrito: 27},
{ id: 200, name: 'Potrero de Caña',idDistrito: 27},
{ id: 201, name: 'Quebrada de Piedra',idDistrito: 27},
{ id: 202, name: 'Veladero',idDistrito: 27},
{ id: 203,name: 'La Palma (Cabecera)',idDistrito: 28},
{ id: 204, name: 'Camoganti',idDistrito: 28},
{ id: 205, name: 'Chepigana',idDistrito: 28},
{ id: 206, name: 'Garachiné',idDistrito: 28},
{ id: 207, name: 'Jaqué',idDistrito: 28},
{ id: 208, name: 'Puerto Piña',idDistrito: 28},
{ id: 209, name: 'Río Congo',idDistrito: 28},
{ id: 210, name: 'Río Iglesias',idDistrito: 28},
{ id: 211, name: 'Sambú',idDistrito: 28},
{ id: 212, name: 'Setegantí',idDistrito: 28},
{ id: 213, name: 'Taimatí',idDistrito: 28},
{ id: 214, name: 'Tucutí',idDistrito: 28},
{ id: 215, name: 'Agua Fría',idDistrito: 28},
{ id: 216, name: 'Cucunatí',idDistrito: 28},
{ id: 217, name: 'Río Congo Arriba',idDistrito: 28},
{ id: 218, name: 'Santa Fe',idDistrito: 28},
{ id: 219, name: 'Pinogana',idDistrito: 28},
{ id: 220, name: 'Boca de Cupé',idDistrito: 29},
{ id: 221, name: 'Paya',idDistrito: 29},
{ id: 222, name: 'Pinogana',idDistrito: 29},
{ id: 223, name: 'Púcuro',idDistrito: 29},
{ id: 224, name:'Yape',idDistrito: 29},
{ id: 225, name:'Yaviza',idDistrito: 29},
{ id: 226, name: 'Metetí',idDistrito: 29},
{ id: 227, name: 'Comarca Kuna de Wargandí',idDistrito: 29},
{ id: 228, name: 'Chitré (Cabecera)',idDistrito: 30},
{ id: 229,name: 'La Arena',idDistrito: 30},
{ id: 230, name: 'Monagrillo',idDistrito: 30},
{ id: 231,name: 'Llano Bonito',idDistrito: 30},
{ id: 232, name: 'San Juan Bautista',idDistrito: 30},
{ id: 233,name: 'Las Minas (Cabecera)',idDistrito: 31},
{ id: 234, name: 'Chepo',idDistrito: 31},
{ id: 235, name: 'Chumical',idDistrito: 31},
{ id: 236,name: 'El Toro',idDistrito: 31},
{ id: 237,name: 'Leones',idDistrito: 31},
{ id: 238, name: 'Quebrada del Rosario',idDistrito: 31},
{ id: 239, name: 'Quebrada El Ciprián',idDistrito: 31},
{ id: 240,name: 'Los Pozos (Cabecera)',idDistrito: 32},
{ id: 241, name: 'Capurí',idDistrito: 32},
{ id: 242,name: 'El Calabacito',idDistrito: 32},
{ id: 243,name: 'El Cedro',idDistrito: 32},
{ id: 244,name: 'La Arena',idDistrito: 32},
{ id: 245,name: 'La Pitaloza',idDistrito: 32},
{ id: 246,name: 'Los Cerritos',idDistrito: 32},
{ id: 247,name: 'Los Cerros de Paja',idDistrito: 32},
{ id: 248,name: 'Las Llanas',idDistrito: 32},
{ id: 249, name: 'Ocú (Cabecera)',idDistrito: 33},
{ id: 250, name: 'Cerro Largo',idDistrito: 33},
{ id: 251,name: 'Los Llanos',idDistrito: 33},
{ id: 252,name: 'Llano Grande',idDistrito: 33},
{ id: 253, name: 'Peñas Chatas',idDistrito: 33},
{ id: 254,name: 'El Tijera',idDistrito: 33},
{ id: 255, name: 'Menchaca',idDistrito: 33},
{ id: 256,name: 'Entradero del Castillo',idDistrito: 33},
{ id: 257, name: 'Parita (Cabecera)',idDistrito: 34},
{ id: 258, name: 'Cabuya',idDistrito: 34},
{ id: 259,name: 'Los Castillos',idDistrito: 34},
{ id: 260,name: 'Llano de la Cruz.',idDistrito: 34},
{ id: 261, name: 'París',idDistrito: 34},
{ id: 262, name: 'Portobelillo',idDistrito: 34},
{ id: 263, name: 'Potuga',idDistrito: 34},
{ id: 264, name: 'Pesé (Cabecera)',idDistrito: 35},
{ id: 265,name: 'Las Cabras',idDistrito: 35},
{ id: 266,name: 'El Pájaro',idDistrito: 35},
{ id: 267,name: 'El Barrero',idDistrito: 35},
{ id: 268,name: 'El Pedregoso',idDistrito: 35},
{ id: 269,name: 'El Ciruelo',idDistrito: 35},
{ id: 270, name: 'Sabanagrande',idDistrito: 35},
{ id: 271, name: 'Rincón Hondo',idDistrito: 35},
{ id: 272, name: 'Santa María (Cabecera)',idDistrito: 36},
{ id: 273, name: 'Chupampa',idDistrito: 36},
{ id: 274,name: 'El Rincón',idDistrito: 36},
{ id: 275,name: 'El Limón',idDistrito: 36},
{ id: 276,name: 'Los Canelos',idDistrito: 36},
{ id: 277, name: 'Guararé (Cabecera)',idDistrito: 37},
{ id: 278,name: 'El Espinal',idDistrito: 37},
{ id: 279,name: 'El Macano',idDistrito: 37},
{ id: 280, name: 'Guararé Arriba',idDistrito: 37},
{ id: 281,name: 'La Enea',idDistrito: 37},
{ id: 282,name: 'La Pasera',idDistrito: 37},
{ id: 283,name: 'Las Trancas',idDistrito: 37},
{ id: 284,name: 'Llano Abajo',idDistrito: 37},
{ id: 285,name: 'El Hato',idDistrito: 37},
{ id: 286, name: 'Perales',idDistrito: 37},
{ id: 287,name: 'Las Tablas (Cabecera)',idDistrito: 38},
{ id: 288, name: 'Bajo Corral',idDistrito: 38},
{ id: 289, name: 'Bayano',idDistrito: 38},
{ id: 290,name: 'El Carate',idDistrito: 38},
{ id: 291,name: 'El Cocal',idDistrito: 38},
{ id: 292,name: 'El Manantial',idDistrito: 38},
{ id: 293,name: 'El Muñoz',idDistrito: 38},
{ id: 294,name: 'El Pedregoso',idDistrito: 38},
{ id: 295,name: 'La Laja',idDistrito: 38},
{ id: 296,name: 'La Miel',idDistrito: 38},
{ id: 297,name: 'La Palma',idDistrito: 38},
{ id: 298,name: 'La Tiza',idDistrito: 38},
{ id: 299,name: 'Las Palmitas',idDistrito: 38},
{ id: 300,name: 'Las Tablas Abajo',idDistrito: 38},
{ id: 301,name: 'Nuario',idDistrito: 38},
{ id: 302, name: 'Palmira',idDistrito: 38},
{ id: 303, name: 'Peña',idDistrito: 38},
{ id: 304, name: 'Río Hondo',idDistrito: 38},
{ id: 305, name: 'San José',idDistrito: 38},
{ id: 306, name: 'San Miguel',idDistrito: 38},
{ id: 307, name: 'Santo Domingo',idDistrito: 38},
{ id: 308, name: 'Sesteadero',idDistrito: 38},
{ id: 309, name: 'Valle Rico',idDistrito: 38},
{ id: 310, name: 'Vallerriquito',idDistrito: 38},
{ id: 311,name: 'La Villa de Los Santos (Cabecera)',idDistrito: 39},
{ id: 312,name: 'El Guásimo',idDistrito: 39},
{ id: 313,name: 'La Colorada',idDistrito: 39},
{ id: 314,name: 'La Espigadilla',idDistrito: 39},
{ id: 315,name: 'Las Cruces',idDistrito: 39},
{ id: 316,name: 'Las Guabas',idDistrito: 39},
{ id: 317,name: 'Los Ángeles',idDistrito: 39},
{ id: 318,name: 'Los Olivos',idDistrito: 39},
{ id: 319,name: 'Llano Largo',idDistrito: 39},
{ id: 320, name: 'Sabanagrande',idDistrito: 39},
{ id: 321, name: 'Santa Ana',idDistrito: 39},
{ id: 322, name: 'Tres Quebradas',idDistrito: 39},
{ id: 323, name: 'Agua Buena',idDistrito: 39},
{ id: 324, name: 'Villa Lourdes',idDistrito: 39},
{ id: 325, name: 'Macaracas (Cabecera)',idDistrito: 40},
{ id: 326, name: 'Bahía Honda',idDistrito: 40},
{ id: 327, name: 'Bajos de Güera',idDistrito: 40},
{ id: 328, name: 'Corozal',idDistrito: 40},
{ id: 329, name: 'Chupá.',idDistrito: 40},
{ id: 330,name: 'El Cedro',idDistrito: 40},
{ id: 331,name: 'Espino Amarillo',idDistrito: 40},
{ id: 332,name: 'La Mesa',idDistrito: 40},
{ id: 333,name: 'Las Palmas',idDistrito: 40},
{ id: 334,name: 'Llano de Piedra',idDistrito: 40},
{ id: 335, name: 'Mogollón',idDistrito: 40},
{ id: 336, name: 'Pedasí (Cabecera)',idDistrito: 41},
{ id: 337,name: 'Los Asientos',idDistrito: 41},
{ id: 338, name: 'Mariabé',idDistrito: 41},
{ id: 339, name: 'Purio',idDistrito: 41},
{ id: 340, name: 'Oria Arriba',idDistrito: 41},
{ id: 341, name: 'Pocrí (Cabecera)',idDistrito: 42},
{ id: 342,name: 'El Cañafístulo',idDistrito: 42},
{ id: 343,name: 'Lajamina',idDistrito: 42},
{ id: 344, name: 'Paraíso',idDistrito: 42},
{ id: 345, name: 'Paritilla',idDistrito: 42},
{ id: 346, name: 'Tonosí (Cabecera)',idDistrito: 43},
{ id: 347, name: 'Altos de Güera',idDistrito: 43},
{ id: 348, name: 'Cañas',idDistrito: 43},
{ id: 349,name: 'El Bebedero',idDistrito: 43},
{ id: 350,name: 'El Cacao',idDistrito: 43},
{ id: 351,name: 'El Cortezo',idDistrito: 43},
{ id: 352,name:'Flores',idDistrito: 43},
{ id: 353, name: 'Guánico',idDistrito: 43},
{ id: 354,name: 'La Tronosa',idDistrito: 43},
{ id: 355, name: 'Cambutal',idDistrito: 43},
{ id: 356,name:'Isla de Cañas',idDistrito: 43},
{ id: 357, name: 'San Miguel (Cabecera)',idDistrito: 44},
{ id: 358,name: 'La Ensenada',idDistrito: 44},
{ id: 359,name: 'La Esmeralda',idDistrito: 44},
{ id: 360,name: 'La Guinea',idDistrito: 44},
{ id: 361, name: 'Pedro González',idDistrito: 44},
{ id: 362, name: 'Saboga',idDistrito: 44},
{ id: 363, name: 'Chepo (Cabecera)',idDistrito: 45},
{ id: 364, name: 'Cañita',idDistrito: 45},
{ id: 365, name: 'Chepillo',idDistrito: 45},
{ id: 366,name: 'El Llano',idDistrito: 45},
{ id: 367,name: 'Las Margaritas',idDistrito: 45},
{ id: 368, name: 'Santa Cruz de Chinina',idDistrito: 45},
{ id: 369, name: 'Comarca Kuna de Madungandí',idDistrito: 45},
{ id: 370, name: 'Tortí',idDistrito: 45},
{ id: 371, name: 'Chimán (Cabecera)',idDistrito: 46},
{ id: 372, name: 'Brujas',idDistrito: 46},
{ id: 373, name: 'Gonzalo Vásquez',idDistrito: 46},
{ id: 374, name: 'Pásiga',idDistrito: 46},
{ id: 375,name: 'Unión Santeña',idDistrito: 46},
{ id: 376, name: 'San Felipe',idDistrito: 47},
{ id: 377,name: 'El Chorrillo',idDistrito: 47},
{ id: 378, name: 'Santa Ana',idDistrito: 47},
{ id: 379,name: 'La Exposición o Calidonia',idDistrito: 47},
{ id: 380, name: 'Curundú',idDistrito: 47},
{ id: 381, name: 'Betania',idDistrito: 47},
{ id: 382, name: 'Bella Vista',idDistrito: 47},
{ id: 383, name: 'Pueblo Nuevo',idDistrito: 47},
{ id: 384, name: 'San Francisco',idDistrito: 47},
{ id: 385, name: 'Parque Lefevre.',idDistrito: 47},
{ id: 386, name: 'Río Abajo',idDistrito: 47},
{ id: 387, name: 'Juan Díaz',idDistrito: 47},
{ id: 388, name: 'Pedregal',idDistrito: 47},
{ id: 389, name: 'Ancón',idDistrito: 47},
{ id: 390, name: 'Chilibre',idDistrito: 47},
{ id: 391,name: 'Las Cumbres',idDistrito: 47},
{ id: 392, name: 'Pacora',idDistrito: 47},
{ id: 393, name: 'San Martín',idDistrito: 47},
{ id: 394, name: 'Tocumen',idDistrito: 47},
{ id: 395,name: 'Las Mañanitas',idDistrito: 47},
{ id: 396,name:'24 de Diciembre',idDistrito: 47},
{ id: 397, name: 'Alcalde Díaz',idDistrito: 47},
{ id: 398,name: 'Ernesto Córdoba Campos',idDistrito: 47},
{ id: 399, name: 'Amelia Denis de Icaza.',idDistrito: 48},
{ id: 400, name: 'Belisario Porras',idDistrito: 48},
{ id: 401, name: 'José Domingo Espinar',idDistrito: 48},
{ id: 402, name: 'Mateo Iturralde',idDistrito: 48},
{ id: 403, name: 'Victoriano Lorenzo',idDistrito: 48},
{ id: 404, name: 'Arnulfo Arias',idDistrito: 48},
{ id: 405, name: 'Belisario Frías',idDistrito: 48},
{ id: 406, name: 'Omar Torrijos',idDistrito: 48},
{ id: 407, name: 'Rufina Alfaro',idDistrito: 48},
{ id: 408, name: 'Taboga (Cabecera)',idDistrito: 49},
{ id: 409, name: 'Otoque Occidente',idDistrito: 49},
{ id: 410, name: 'Otoque Oriente',idDistrito: 49},
{ id: 411, name: 'Atalaya (Cabecera)',idDistrito: 50},
{ id: 412,name: 'El Barrito',idDistrito: 50},
{ id: 413,name: 'La Montañuela',idDistrito: 50},
{ id: 414,name: 'La Carrillo',idDistrito: 50},
{ id: 415, name: 'San Antonio',idDistrito: 50},
{ id: 416, name: 'Calobre (Cabecera)',idDistrito: 51},
{ id: 417, name: 'Barnizal',idDistrito: 51},
{ id: 418, name: 'Chitra',idDistrito: 51},
{ id: 419,name: 'El Cocla',idDistrito: 51},
{ id: 420,name: 'El Potrero',idDistrito: 51},
{ id: 421,name: 'La Laguna',idDistrito: 51},
{ id: 422,name: 'La Raya de Calobre',idDistrito: 51},
{ id: 423,name: 'La Tetilla',idDistrito: 51},
{ id: 424,name: 'La Yeguada',idDistrito: 51},
{ id: 425,name: 'Las Guías',idDistrito: 51},
{ id: 426, name: 'Monjarás',idDistrito: 51},
{ id: 427, name: 'San José',idDistrito: 51},
{ id: 428, name: 'Cañazas (Cabecera)',idDistrito: 52},
{ id: 429, name: 'Cerro Plata',idDistrito: 52},
{ id: 430,name: 'El Picador',idDistrito: 52},
{ id: 431,name: 'Los Valles',idDistrito: 52},
{ id: 432, name: 'San José',idDistrito: 52},
{ id: 433, name: 'San Marcelo',idDistrito: 52},
{ id: 434,name: 'El Aromillo',idDistrito: 52},
{ id: 435,name: 'Las Cruces',idDistrito: 52},
{ id: 436,name: 'La Mesa (Cabecera)',idDistrito: 53},
{ id: 437, name: 'Bisvalles',idDistrito: 53},
{ id: 438, name: 'Boró',idDistrito: 53},
{ id: 439,name: 'Llano Grande',idDistrito: 53},
{ id: 440, name: 'San Bartolo',idDistrito: 53},
{ id: 441,name: 'Los Milagros',idDistrito: 53},
{ id: 442,name: 'El Higo',idDistrito: 53},
{ id: 443,name: 'Las Palmas (Cabecera)',idDistrito: 54},
{ id: 444, name: 'Cerro de Casa',idDistrito: 54},
{ id: 445, name: 'Corozal',idDistrito: 54},
{ id: 446,name: 'El María',idDistrito: 54},
{ id: 447,name: 'El Prado',idDistrito: 54},
{ id: 448,name: 'El Rincón',idDistrito: 54},
{ id: 449,name: 'Lolá',idDistrito: 54},
{ id: 450, name: 'Pixvae',idDistrito: 54},
{ id: 451, name: 'Puerto Vidal',idDistrito: 54},
{ id: 452, name: 'San Martín de Porres',idDistrito: 54},
{ id: 453, name: 'Viguí',idDistrito: 54},
{ id: 454,name: 'Zapotillo',idDistrito: 54},
{ id: 455, name: 'Manuel E. Amador Terrero',idDistrito: 54},
{ id: 456, name: 'Montijo (Cabecera)',idDistrito: 55},
{ id: 457, name: 'Gobernadora',idDistrito: 55},
{ id: 458,name: 'La Garceana',idDistrito: 55},
{ id: 459,name: 'Leones',idDistrito: 55},
{ id: 460, name: 'Pilón',idDistrito: 55},
{ id: 461, name: 'Cébaco',idDistrito: 55},
{ id: 462, name: 'Costa Hermosa',idDistrito: 55},
{ id: 463,name: 'Unión del Norte',idDistrito: 55},
{ id: 464, name: 'Río de Jesús (Cabecera)',idDistrito: 56},
{ id: 465,name: 'Las Huacas',idDistrito: 56},
{ id: 466,name: 'Los Castillos',idDistrito: 56},
{ id: 467,name: 'Utira',idDistrito: 56},
{ id: 468, name: 'Catorce de Noviembre',idDistrito: 56},
{ id: 469, name: 'San Francisco (Cabecera)',idDistrito: 57},
{ id: 470, name: 'Corral Falso',idDistrito: 57},
{ id: 471,name: 'Los Hatillos',idDistrito: 57},
{ id: 472, name: 'Remance',idDistrito: 57},
{ id: 473, name: 'San Juan',idDistrito: 57},
{ id: 474, name: 'San José',idDistrito: 57},
{ id: 475, name: 'Santa Fe (Cabecera)',idDistrito: 58},
{ id: 476, name: 'Calovébora',idDistrito: 58},
{ id: 477,name: 'El Alto',idDistrito: 58},
{ id: 478,name: 'El Cuay',idDistrito: 58},
{ id: 479,name: 'El Pantano',idDistrito: 58},
{ id: 480, name: 'Gatú o Gatucito',idDistrito: 58},
{ id: 481, name: 'Río Luis',idDistrito: 58},
{ id: 482, name: 'Rubén Cantú',idDistrito: 58},
{ id: 483, name: 'Santiago (Cabecera)',idDistrito: 59},
{ id: 484,name: 'La Colorada',idDistrito: 59},
{ id: 485,name: 'La Peña',idDistrito: 59},
{ id: 486,name: 'La Raya de Santa María',idDistrito: 59},
{ id: 487, name: 'Ponuga',idDistrito: 59},
{ id: 488, name: 'San Pedro del Espino',idDistrito: 59},
{ id: 489, name: 'Canto del Llano',idDistrito: 59},
{ id: 490,name: 'Los Algarrobos',idDistrito: 59},
{ id: 491, name: 'Carlos Santana Ávila',idDistrito: 59},
{ id: 492,name: 'Edwin Fábrega',idDistrito: 59},
{ id: 493, name: 'San Martín de Porres',idDistrito: 59},
{ id: 494,name: 'Urracá',idDistrito: 59},
{ id: 495, name: 'Soná (Cabecera)',idDistrito: 60},
{ id: 496, name: 'Bahía Honda',idDistrito: 60},
{ id: 497, name: 'Calidonia',idDistrito: 60},
{ id: 498, name: 'Cativé',idDistrito: 60},
{ id: 499,name: 'El Marañón',idDistrito: 60},
{ id: 500, name: 'Guarumal',idDistrito: 60},
{ id: 501,name: 'La Soledad',idDistrito: 60},
{ id: 502, name: 'Quebrada de Oro',idDistrito: 60},
{ id: 503, name: 'Río Grande',idDistrito: 60},
{ id: 504, name: 'Rodeo Viejo',idDistrito: 60},
{ id: 505, name: 'Hicaco',idDistrito: 60},
{ id: 506,name: 'Llano de Catival o Mariato (Cabecera)',idDistrito: 61},
{ id: 507, name: 'Arenas',idDistrito: 61},
{ id: 508,name: 'El Cacao',idDistrito: 61},
{ id: 509, name: 'Quebro',idDistrito: 61},
{ id: 510, name: 'Tebario',idDistrito: 61},
{ id: 511, name:'Narganá (Cabecera)',idDistrito: 62},
{ id: 512, name: 'Ailigandí',idDistrito: 62},
{ id: 513, name: 'Puerto Obaldía',idDistrito: 62},
{ id: 514, name: 'Tubualá',idDistrito: 62},
{ id: 515, name: 'Cirilo Guainora (Cabecera)',idDistrito: 63},
{ id: 516,name: 'Lajas Blancas',idDistrito: 63},
{ id: 517, name: 'Manuel Ortega',idDistrito: 63},
{ id: 518, name: 'Río Sábalo',idDistrito: 64},
{ id: 519, name: 'Jingurudó',idDistrito: 64},
{ id: 520, name: 'Soloy (Cabecera)',idDistrito: 65},
{ id: 521, name: 'Boca de Balsa',idDistrito: 65},
{ id: 522, name: 'Camarón Arriba',idDistrito: 65},
{ id: 523, name: 'Cerro Banco',idDistrito: 65},
{ id: 524, name: 'Cerro de Patena',idDistrito: 65},
{ id: 525,name: 'Emplanada de Chorcha',idDistrito: 65},
{ id: 526,name:'Nämnoni',idDistrito: 65},
{ id: 527,name:'Niba',idDistrito: 65},
{ id: 528, name: 'Hato Pilón (Cabecera)',idDistrito: 66},
{ id: 529, name: 'Cascabel',idDistrito: 66},
{ id: 530, name: 'Hato Corotú',idDistrito: 66},
{ id: 531, name: 'Hato Culantro',idDistrito: 66},
{ id: 532, name: 'Hato Jobo',idDistrito: 66},
{ id: 533, name: 'Hato Julí',idDistrito: 66},
{ id: 534, name: 'Quebrada de Loro',idDistrito: 66},
{ id: 535, name: 'Salto Dupí',idDistrito: 66},
{ id: 536, name: 'Chichica (Cabecera)',idDistrito: 67},
{ id: 537, name: 'Alto Caballero',idDistrito: 67},
{ id: 538, name: 'Bakama',idDistrito: 67},
{ id: 539, name: 'Cerro Caña',idDistrito: 67},
{ id: 540, name: 'Cerro Puerco',idDistrito: 67},
{ id: 541, name: 'Krüa',idDistrito: 67},
{ id: 542, name: 'Maraca',idDistrito: 67},
{ id: 543,name: 'Nibra',idDistrito: 67},
{ id: 544, name: 'Peña Blanca',idDistrito: 67},
{ id: 545, name: 'Roka',idDistrito: 67},
{ id: 546, name: 'Sitio Prado',idDistrito: 67},
{ id: 547,name: 'Ümani',idDistrito: 67},
{ id: 548, name: 'Cerro Iglesias (Cabecera)',idDistrito: 68},
{ id: 549, name: 'Hato Chamí',idDistrito: 68},
{ id: 550, name: 'Jädaberi',idDistrito: 68},
{ id: 551,name: 'Lajero',idDistrito: 68},
{ id: 552, name: 'Susama',idDistrito: 68},
{ id: 553, name: 'Buenos Aires (Cabecera)',idDistrito: 69},
{ id: 554, name: 'Agua de Salud',idDistrito: 69},
{ id: 555, name: 'Alto de Jesús',idDistrito: 69},
{ id: 556, name: 'Cerro Pelado',idDistrito: 69},
{ id: 557,name: 'El Bale',idDistrito: 69},
{ id: 558,name: 'El Paredón',idDistrito: 69},
{ id: 559,name: 'El Piro',idDistrito: 69},
{ id: 560, name: 'Guayabito',idDistrito: 69},
{ id: 561, name: 'Güibale',idDistrito: 69},
{ id: 562,name: 'El Peñon',idDistrito: 69},
{ id: 563,name: 'El Piro No. 2 (Muakwata Kubu)',idDistrito: 69},
{ id: 564, name: 'Bisira (Cabecera)',idDistrito: 70},
{ id: 565, name: 'Cantalante',idDistrito: 70},
{ id: 566, name: 'Guoroni',idDistrito: 70},
{ id: 567, name: 'Kankintú',idDistrito: 70},
{ id: 568, name: 'Mününi',idDistrito: 70},
{ id: 569, name: 'Piedra Roja',idDistrito: 70},
{ id: 570, name: 'Tolote',idDistrito: 70},
{ id: 571, name: 'Kusapín (Cabecera)',idDistrito: 71},
{ id: 572, name: 'Bahía Azul',idDistrito: 71},
{ id: 573, name: 'Calovébora o Santa Catalina',idDistrito: 71},
{ id: 574,name: 'Loma Yuca',idDistrito: 71},
{ id: 575, name: 'Río Chiriquí',idDistrito: 71},
{ id: 576, name: 'Tobobe',idDistrito: 71},
{ id: 577, name: 'Valle Bonito',idDistrito: 71},
{ id: 578, name: 'Samboa (Cabecera)',idDistrito: 72},
{ id: 579, name: 'Büri',idDistrito: 72},
{ id: 580, name: 'Guariviara',idDistrito: 72},
{ id: 581, name: 'Man Creek',idDistrito: 72},
{ id: 582, name: 'Tuwai',idDistrito: 72},
{ id: 583, name: 'Santa Catalina o Calovébora (Bladeshia) (Cabecera)',idDistrito: 73},
{ id: 584, name: 'Alto Bilingüe (Gdogüeshia)',idDistrito: 73},
{ id: 585,name: 'Loma Yuca (Ljuicho)',idDistrito: 73},
{ id: 586, name: 'San Pedrito (Jiküi)',idDistrito: 73},
{ id: 587, name: 'Valle Bonito (Dogata)',idDistrito: 73},
{ id: 588, name: 'Arraiján (Cabecera)',idDistrito: 74},
{ id: 589, name: 'Juan Demóstenes Arosemena',idDistrito: 74},
{ id: 590, name:' Nuevo Emperador',idDistrito: 74},
{ id: 591, name: 'Santa Clara',idDistrito: 74},
{ id: 592, name: 'Veracruz',idDistrito: 74},
{ id: 593, name: 'Vista Alegre',idDistrito: 74},
{ id: 594, name: 'Burunga',idDistrito: 74},
{ id: 595, name: 'Cerro Silvestre',idDistrito: 74},
{ id: 596, name: 'Capira (Cabecera)',idDistrito: 75},
{ id: 597, name: 'Caimito',idDistrito: 75},
{ id: 598, name: 'Campana',idDistrito: 75},
{ id: 599, name: 'Cermeño',idDistrito: 75},
{ id: 600, name: 'Cirí de los Sotos',idDistrito: 75},
{ id: 601, name: 'Cirí Grande',idDistrito: 75},
{ id: 602,name: 'El Cacao',idDistrito: 75},
{ id: 603,name: 'La Trinidad',idDistrito: 75},
{ id: 604,name: 'Las Ollas Arriba',idDistrito: 75},
{ id: 605,name: 'Lídice',idDistrito: 75},
{ id: 606, name: 'Villa Carmen',idDistrito: 75},
{ id: 607, name: 'Villa Rosario',idDistrito: 75},
{ id: 608, name: 'Santa Rosa',idDistrito: 75},
{ id: 609, name: 'Chame (Cabecera)',idDistrito: 76},
{ id: 610, name: 'Bejuco',idDistrito: 76},
{ id: 611, name: 'Buenos Aires',idDistrito: 76},
{ id: 612, name: 'Cabuya',idDistrito: 76},
{ id: 613, name: 'Chicá',idDistrito: 76},
{ id: 614,name: 'El Líbano',idDistrito: 76},
{ id: 615,name: 'Las Lajas',idDistrito: 76},
{ id: 616,name: 'Nueva Gorgona',idDistrito: 76},
{ id: 617, name: 'Punta Chame',idDistrito: 76},
{ id: 618, name: 'Sajalices',idDistrito: 76},
{ id: 619, name: 'Sorá',idDistrito: 76},
{ id: 620, name: 'Barrio Balboa',idDistrito: 77},
{ id: 621, name: 'Barrio Colón',idDistrito: 77},
{ id: 622, name: 'Amador',idDistrito: 77},
{ id: 623, name: 'Arosemena',idDistrito: 77},
{ id: 624,name: 'El Arado',idDistrito: 77},
{ id: 625,name: 'El Coco',idDistrito: 77},
{ id: 626,name:'Feuillet',idDistrito: 77},
{ id: 627, name: 'Guadalupe',idDistrito: 77},
{ id: 628, name: 'Herrera',idDistrito: 77},
{ id: 629, name: 'Hurtado',idDistrito: 77},
{ id: 630,name: 'Iturralde',idDistrito: 77},
{ id: 631,name: 'La Represa',idDistrito: 77},
{ id: 632,name: 'Los Díaz',idDistrito: 77},
{ id: 633, name: 'Mendoza',idDistrito: 77},
{ id: 634, name: 'Obaldía',idDistrito: 77},
{ id: 635, name: 'Playa Leona',idDistrito: 77},
{ id: 636, name: 'Puerto Caimito',idDistrito: 77},
{ id: 637, name: 'Santa Rita',idDistrito: 77},
{ id: 638, name: 'San Carlos (Cabecera)',idDistrito: 78},
{ id: 639,name: 'El Espino',idDistrito: 78},
{ id: 640,name: 'El Higo',idDistrito: 78},
{ id: 641, name: 'Guayabito',idDistrito: 78},
{ id: 642,name: 'La Ermita',idDistrito: 78},
{ id: 643,name: 'La Laguna',idDistrito: 78},
{ id: 644,name: 'Las Uvas',idDistrito: 78},
{ id: 645,name: 'Los Llanitos',idDistrito: 78},
{ id: 646, name: 'San José',idDistrito: 78}
]