export const distritos = [
    { id: 1, name: 'Bocas del Toro', idProvincia: 1 },
    { id: 2, name: 'Changuinola', idProvincia: 1 },
    { id: 3, name: 'Chiriquí Grande', idProvincia: 1 },
    { id: 4, name: 'Aguadulce', idProvincia: 2 },
    { id: 5, name: 'Antón', idProvincia: 2 },
    { id: 6, name: 'La Pintada', idProvincia: 2 },
    { id: 7, name: 'Natá', idProvincia: 2 },
    { id: 8, name: 'Olá', idProvincia: 2 },
    { id: 9, name: 'Penonomé', idProvincia: 2 },
    { id: 10, name: 'Colón', idProvincia: 3 },
    { id: 11, name: 'Chagres', idProvincia: 3 },
    { id: 12, name: 'Donoso', idProvincia: 3 },
    { id: 13, name: 'Portobelo', idProvincia: 3 },
    { id: 14, name: 'Santa Isabel', idProvincia: 3 },
    { id: 15, name: 'Alanje', idProvincia: 4 },
    { id: 16, name: 'Barú', idProvincia: 4 },
    { id: 17, name: 'Boqueró', idProvincia: 4 },
    { id: 18, name: 'Boquet', idProvincia: 4 },
    { id: 19, name: 'Bugaba', idProvincia: 4 },
    { id: 20, name: 'David', idProvincia: 4 },
    { id: 21, name: 'Dolega', idProvincia: 4 },
    { id: 22, name: 'Gualaca', idProvincia: 4 },
    { id: 23, name: 'Remedios', idProvincia: 4 },
    { id: 24, name: 'Renacimiento', idProvincia: 4 },
    { id: 25, name: 'San Félix', idProvincia: 4 },
    { id: 26, name: 'San Lorenzo', idProvincia: 4 },
    { id: 27, name: 'Tolé', idProvincia: 4 },
    { id: 28, name: 'Chepigana', idProvincia: 5 },
    { id: 29, name: 'El Real de Santa María (Cabecera)', idProvincia: 5 },
    { id: 30, name: 'Chitré', idProvincia: 6 },
    { id: 31, name: 'Las Minas', idProvincia: 6 },
    { id: 32, name: 'Los Pozos', idProvincia: 6 },
    { id: 33, name: 'Ocú', idProvincia: 6 },
    { id: 34, name: 'Parita', idProvincia: 6 },
    { id: 35, name: 'Pesé', idProvincia: 6 },
    { id: 36, name: 'Santa María', idProvincia: 6 },
    { id: 37, name: 'Guararé', idProvincia: 7 },
    { id: 38, name: 'Las Tablas', idProvincia: 7 },
    { id: 39, name: 'Los Santos', idProvincia: 7 },
    { id: 40, name: 'Macaracas', idProvincia: 7 },
    { id: 41, name: 'Pedasí', idProvincia: 7 },
    { id: 42, name: 'Pocrí', idProvincia: 7 },
    { id: 43, name: 'Tonosí', idProvincia: 7 },
    { id: 44, name: 'Balboa', idProvincia: 8 },
    { id: 45, name: 'Chepo', idProvincia: 8 },
    { id: 46, name: 'Chimán', idProvincia: 8 },
    { id: 47, name: 'Panamá', idProvincia: 8 },
    { id: 48, name: 'San Miguelito', idProvincia: 8 },
    { id: 49, name: 'Taboga', idProvincia: 8 },
    { id: 50, name: 'Atalaya', idProvincia: 9 },
    { id: 51, name: 'Calobre', idProvincia: 9 },
    { id: 52, name: 'Cañazas', idProvincia: 9 },
    { id: 53, name: 'La Mesa', idProvincia: 9 },
    { id: 54, name: 'Las Palmas', idProvincia: 9 },
    { id: 55, name: 'Montijo', idProvincia: 9 },
    { id: 56, name: 'Río de Jesús', idProvincia: 9 },
    { id: 57, name: 'San Francisco', idProvincia: 9 },
    { id: 58, name: 'Santa Fe', idProvincia: 9 },
    { id: 59, name: 'Santiago', idProvincia: 9 },
    { id: 60, name: 'Soná', idProvincia: 9 },
    { id: 61, name: 'Mariato', idProvincia: 9 },
    { id: 62, name: 'Comarca Kuna Yala', idProvincia: 10 },
    { id: 63, name: 'Cémaco', idProvincia: 11 },
    { id: 64, name: 'Sambú', idProvincia: 11 },
    { id: 65, name: 'Besiko', idProvincia: 12 },
    { id: 66, name: 'Mironó', idProvincia: 12 },
    { id: 67, name: 'Müna', idProvincia: 12 },
    { id: 68, name: 'Nole Duima', idProvincia: 12 },
    { id: 69, name: 'Ñürüm', idProvincia: 12 },
    { id: 70, name: 'Kankintú', idProvincia: 12 },
    { id: 71, name: 'Kusapín', idProvincia: 12 },
    { id: 72, name: 'Jirondai', idProvincia: 12 },
    { id: 73, name: 'Santa Catalina o Calovébora (Bladeshia)', idProvincia: 12 },
    { id: 74, name: 'Arraiján', idProvincia: 13 },
    { id: 75, name: 'Capira', idProvincia: 13 },
    { id: 76, name: 'Chame', idProvincia: 13 },
    { id: 77, name: 'La Chorrera', idProvincia: 13 },
    { id: 78, name: 'San Carlos', idProvincia: 13 }
];
